//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee
{
    using System;
    
    public enum SkillSetType : int
    {
        WebDeveloper = 1,
        WindowsDeveloepr = 2,
        WindowsDeveloperClassic = 3,
        Designer = 4
    }
}
