//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technology
    {
        public int TechnologyId { get; set; }
        public string SkillsetName { get; set; }
        public string Version { get; set; }
        public string YearsOfExperience { get; set; }
        public int EmployeeEmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
